services:
  - type: web
    name: retro-games
    env: ruby
    runtime: ruby
    buildCommand: bundle install && bundle exec rake assets:precompile
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: enabled
      - key: SECRET_KEY_BASE
        generateValue: true
